[icons.overrides]
cpu = ""
memory_mem = ""
thermometer = ""

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
warning = 85
alert = 90
format = "{icon} {used}/{total}"

[[block]]
block = "temperature"
collapsed = false
interval = 3
format = "{max}"
chip = "*-isa-*"
inputs = ["CPUTIN", "SYSTIN"]

[[block]]
block = "cpu"
interval = 3
format = "{utilization} {frequency}"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}({mem_used_percents})"
display_type = "memory"
icons = true
clickable = false
interval = 5
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "nvidia_gpu"
gpu_id = 0
label = ""
show_memory = false
show_clocks = false
interval = 3

[[block]]
block = "networkmanager"
on_click = "alacritty -e nmtui"
interface_name_exclude = ["br\\-[0-9a-f]{12}", "docker\\d+", "virbr0"]
interface_name_include = []
ap_format = "{ssid^10}"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = ""
critical_updates_regex = "(linux|linux-lts|linux-zen)"
aur_command = "paru -Qua"

[[block]]
block = "sound"
format = "{volume}"

[[block]]
block = "time"
format = "%a %d/%m %R"
timezone = "Europe/Berlin"
interval = 60
locale = "de_DE"

[[block]]
block = "custom"
command = "lsmod | grep uvcvideo | head --lines 1 | awk '{if ($3 == \"0\") {print \"﫞\"} else {print \"\"}}'"
interval = 5

[theme]
name = "semi-native"

[icons]
name = "material-nf"
