
format = """
┌─[](#9A348E)\
$username\
[](bg:#DA627D fg:#9A348E)\
$directory\
[](fg:#DA627D bg:#FCA17D)\
$git_commit\
$git_status\
[](fg:#FCA17D bg:#86BBD8)\
${custom.todos}\
${custom.fixme}\
[](fg:#86BBD8 bg:#33658A)\
$time\
[](fg:#33658A) $cmd_duration\n\r\
└$jobs$character$nix_shell\
"""

add_newline = true

[username]
show_always = true
style_user = "bg:#9A348E"
style_root = "bg:#9A348E"
format = '[$user ]($style)'

[directory]
style = "bg:#DA627D"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = ""

[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = " "

[git_branch]
symbol = ""
style = "bg:#FCA17D"
format = '[[ $symbol $branch ](fg:#33658A bg:#FCA17D)]($style)'

[git_commit]
style = "bg:#FCA17D"
format = '[[  $hash $tag](fg:#33658A bg:#FCA17D)]($style)'

[git_status]
style = "bg:#FCA17D"
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = '[[($all_status$ahead_behind )](fg:#0A348E bg:#FCA17D)]($style)'

[nodejs]
style = "bg:#86BBD8"
format = '[[ $symbol($version) ](fg:#33658A bg:#86BBD8)]($style)'

[rust]
symbol = " "
style = "bg:#86BBD8"
format = '[[ $symbol($version) ](fg:#33658A bg:#86BBD8)]($style)'

[time]
disabled = false
time_format = "%R"                           # Hour:Minute Format
style = "bg:#33658A"
format = '[[  $time ](bg:#33658A)]($style)'

[jobs]
symbol = "+"
format = '\[[$symbol$number]($style)\]'

[nix_shell]
disabled = false
symbol = " "
format = '[$name $symbol]($style)'

[character]
success_symbol = '\$'
error_symbol = '[✗](bold red)'

[custom.todos]
description = "todos"
when = "git rev-parse --show-toplevel"
command = "rg -i --count \"todo\\W\" (git rev-parse --show-toplevel) | awk -F: 'BEGIN { count = 0 } { count = count + $2 } END { print count }'"
style = " =  #86BBD8"
format = '[[ $output Todos ](fg:#33658A bg:#86BBD8)]($style)'

[custom.fixme]
description = "todos"
when = "git rev-parse --show-toplevel"
command = "rg -i --count \"fixme\\W\" (git rev-parse --show-toplevel) | awk -F: 'BEGIN { count = 0 } { count = count + $2 } END { print count }'"
style = " =  #86BBD8"
format = '[[$output Fixme ](fg:#33658A bg:#86BBD8)]($style)'

[custom.jj]
description = "jj branch"
command = "jj log -r 'git_head()' | head -n 1 | awk '{print $(NF - 1)}'"
format = "[[$output](fg:#0A348E bg:#FCA17D)]($style)"
disabled = false
