
[user]
name = "Olivier Lemoine"
email = "olivier.lemoine@432technologies.com"

[alias]
close = ["commit"]
l = ["log", "-r", "(heads(remote_branches())..@):"]
la = ["log", "-r", "all()"]

[ui]
editor = "nvim"
diff_editor = "vimdiff"
