
[user]
name = "Olivier Lemoine"
email = "olivier.lemoine@432technologies.com"

[alias]
close = ["commit"]
l = ["log", "-r", "(heads(remote_branches())..@):"]
la = ["log", "-r", "all()"]
lm = ["log", "-r", "::@ ~ ::main"]

[ui]
editor = "hx"
diff-editor = "code --wait --diff --new-window $left $right"
diff.format = "git"
graph.style = "ascii"
log-word-wrap = false
